# Generated by Django 5.2.5 on 2025-09-01 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Номер заказа')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Клиент')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('has_whatsapp', models.BooleanField(default=True, verbose_name='Есть WhatsApp')),
                ('whatsapp_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон WhatsApp')),
                ('item', models.CharField(max_length=200, verbose_name='Изделие')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('done', 'Готов'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок готовности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Выставлен')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lds_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во ЛДСП')),
                ('facades_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='м² фасады')),
                ('material_type', models.CharField(blank=True, choices=[('lds', 'ЛДСП'), ('paint', 'Краска'), ('film', 'Плёнка')], max_length=20, null=True, verbose_name='Материал')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок сдачи')),
                ('status', models.CharField(choices=[('procurement', 'Закуп'), ('design', 'Оформление'), ('production', 'Производство')], default='procurement', max_length=20, verbose_name='Статус')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Операция')),
                ('assignee', models.CharField(blank=True, max_length=200, verbose_name='Ответственный')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('doing', 'Выполняется'), ('done', 'Готово')], default='todo', max_length=50, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.order', verbose_name='Заказ')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lds_color1', models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 1 (листов)')),
                ('pvc_color1', models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 1 (метров)')),
                ('lds_color2', models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 2 (листов)')),
                ('pvc_color2', models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 2 (метров)')),
                ('lds_color3', models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 3 (листов)')),
                ('pvc_color3', models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 3 (метров)')),
                ('lds_color4', models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 4 (листов)')),
                ('pvc_color4', models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 4 (метров)')),
                ('tabletop_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Столешница (шт.)')),
                ('tabletop_length_3m', models.BooleanField(default=True, verbose_name='3 метра')),
                ('hdf_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='ХДФ задняя стенка (листов)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_sheet', to='core.order')),
            ],
        ),
    ]
