# Generated by Django 5.2.5 on 2025-09-01 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за единицу'),
        ),
    ]
