# Generated by Django 5.2.5 on 2025-09-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_created_date_alter_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesheet',
            name='lds_color10',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 10 (листов)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='lds_color5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 5 (листов)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='lds_color6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 6 (листов)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='lds_color7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 7 (листов)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='lds_color8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 8 (листов)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='lds_color9',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ЛДСП цвет 9 (листов)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_color10',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 10 (метров)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_color5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 5 (метров)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_color6',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 6 (метров)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_color7',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 7 (метров)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_color8',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 8 (метров)'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_color9',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ПВХ цвет 9 (метров)'),
        ),
    ]
