# Generated by Django 5.2.6 on 2025-09-06 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_facade_and_purchase_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='facadesheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='designer_services_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Услуги дизайнера'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color10_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 10 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color10_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 10 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color10_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 10'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color10_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 10 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color2_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 2 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color2_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 2 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color2_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 2'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color2_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 2 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color3_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 3 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color3_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 3 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color3_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 3'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color3_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 3 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color4_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 4 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color4_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 4 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color4_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 4'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color4_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 4 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color5_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 5 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color5_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 5 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color5_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 5'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color5_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 5 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color6_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 6 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color6_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 6 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color6_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 6'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color6_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 6 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color7_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 7 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color7_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 7 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color7_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 7'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color7_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 7 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color8_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 8 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color8_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 8 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color8_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 8'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color8_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 8 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color9_fresa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 9 (Фреза)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color9_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фасады пленка цвет 9 (м2)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color9_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фасады пленка цвет 9'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_color9_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка цвет 9 (сумма)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='film_total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады пленка сумма (общая)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='material_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завоза материала'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facade_sheet', to='core.order'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='paint_total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Фасады покраска сумма (общая)'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='services_paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты услуг'),
        ),
        migrations.AddField(
            model_name='facadesheet',
            name='spec_text',
            field=models.TextField(blank=True, null=True, verbose_name='Спецификация'),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group10_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group10_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group1_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group1_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group2_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group2_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group3_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group3_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group4_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group4_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group5_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group5_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group6_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group6_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group7_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group7_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group8_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group8_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group9_corpus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='group9_facade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color1',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color10',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color2',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color3',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color4',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color5',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color6',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color7',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color8',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchasesheet',
            name='pvc_wide_color9',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchasesheet',
            name='tabletop_length_3m',
            field=models.BooleanField(default=False, verbose_name='3 метра'),
        ),
    ]
