# Generated by Django 5.2.6 on 2025-09-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_facadesheet_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facadesheet',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facade_sheet', to='core.order'),
        ),
    ]
