# Generated by Django 5.2.5 on 2025-09-07 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_facadesheet_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('purchase_sheet', 'Лист закупа'), ('contract', 'Договор')], max_length=32)),
                ('action', models.CharField(choices=[('created', 'Создание'), ('updated', 'Изменение')], default='updated', max_length=16)),
                ('diff_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='core.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
