# Generated by Django 5.2.5 on 2025-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='cost_ldsp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость работ по ЛДСП'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='cost_pvc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость ПВХ узкая'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='cost_pvc_wide',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость ПВХ широкая'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='qty_ldsp_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого ЛДСП (листов)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='qty_pvc_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого ПВХ узкая (м)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='qty_pvc_wide_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого ПВХ широкая (м)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='sums_ldsp',
            field=models.JSONField(blank=True, default=dict, verbose_name='Суммы ЛДСП по цветам (листов)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='sums_pvc',
            field=models.JSONField(blank=True, default=dict, verbose_name='Суммы ПВХ (узкая) по цветам (м)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='sums_pvc_wide',
            field=models.JSONField(blank=True, default=dict, verbose_name='Суммы ПВХ (широкая) по цветам (м)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итоговая стоимость'),
        ),
    ]
