# Generated by Django 5.2.5 on 2025-09-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_calculation_cost_ldsp_calculation_cost_pvc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='cost_countertop',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость столешниц'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='cost_facades',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость фасадов (итого)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='cost_hdf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость ХДФ'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='cost_ldsp_prisadka',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость ЛДСП (присадка)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='cost_ldsp_raspil',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость ЛДСП (распил)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='cost_misc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость прочее (итого)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='countertop_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Столешница (шт.)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='hdf_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ХДФ задняя стенка (листов)'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='cost_ldsp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость ЛДСП (итого)'),
        ),
        migrations.CreateModel(
            name='CalculationFacadeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Квадратура, м²')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facade_items', to='core.calculation')),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.priceitem')),
            ],
            options={
                'verbose_name': 'Строка фасада',
                'verbose_name_plural': 'Строки фасадов',
            },
        ),
    ]
