# Generated by Django 5.2.5 on 2025-09-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_calculation_cost_countertop_calculation_cost_facades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='last_price_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calculation',
            name='price_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
