# Generated by Django 5.2.5 on 2025-09-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_calculation_last_price_sync_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='cost_design_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость «Дизайн проект» (итого)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='design_facade_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Фасады — дизайн (стоимость)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='design_facade_sheets',
            field=models.PositiveIntegerField(default=0, verbose_name='Фасады — листов (по 5 м²)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='design_ldsp_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ЛДСП — дизайн (стоимость)'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='was_saved',
            field=models.BooleanField(default=False, verbose_name='Пользователь сохранял расчёт'),
        ),
    ]
