# Generated by Django 5.2.5 on 2025-09-11 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_calculation_cost_design_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итоговая стоимость')),
                ('amount_design', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итого «Дизайн проект»')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Итого к оплате')),
                ('methods', models.JSONField(blank=True, default=list, verbose_name='Вид оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время оплаты')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кассир')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
