# Generated by Django 5.2.5 on 2025-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_payment_unique_payment_per_order'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='priceitem',
            constraint=models.UniqueConstraint(fields=('group', 'title'), name='unique_priceitem_title_per_group'),
        ),
    ]
