# Generated by Django 5.2.5 on 2025-09-12 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_priceitem_unique_priceitem_title_per_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='cost_additional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость дополнительно (итого)'),
        ),
        migrations.CreateModel(
            name='CalculationAdditionalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Стоимость')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_items', to='core.calculation')),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.priceitem')),
            ],
            options={
                'verbose_name': 'Доп. позиция (расчёт)',
                'verbose_name_plural': 'Доп. позиции (расчёт)',
            },
        ),
    ]
