# Generated by Django 5.2.5 on 2025-10-02 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_calculation_cost_additional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.payment',),
        ),
        migrations.CreateModel(
            name='WarehouseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('accepted', 'Принято')], default='draft', max_length=20)),
                ('qty_ldsp_2750x1830', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('qty_ldsp_2800x2070', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('qty_pvc_narrow_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty_pvc_wide_m', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty_hdf_sheets', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('qty_countertop_pcs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('countertop_edge_present', models.BooleanField(default=False)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('driver_phone', models.CharField(blank=True, max_length=50)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='warehouse_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_receipts', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='core.warehousereceipt')),
            ],
        ),
    ]
