# Generated by Django 5.2.5 on 2025-10-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_receipt_warehousereceipt_warehousedraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousereceipt',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='warehousereceipt',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='warehousereceipt',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
