# Generated by Django 5.2.5 on 2025-10-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_warehousereceipt_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('calc', 'Расчёт'), ('payment', 'Закуп'), ('warehouse', 'Договор'), ('work', 'В работе')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
