# Generated by Django 5.2.5 on 2025-10-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousereceipt',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
