# Generated by Django 5.2.5 on 2025-10-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_warehousereceipt_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_facades',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
