# Generated by Django 5.2.5 on 2025-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_payment_amount_facades'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_payment_per_order',
        ),
        migrations.AddField(
            model_name='payment',
            name='calc_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Снимок расчёта на момент оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('full', 'Полная'), ('diff', 'Разница')], default='full', max_length=10, verbose_name='Режим оплаты'),
        ),
    ]
