# Generated by Django 5.2.5 on 2025-10-08 08:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_payment_unique_payment_per_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('kitchen', 'Кухня'), ('wardrobe', 'Шкаф'), ('closet', 'Гардероб'), ('misc', 'Разное')], default='kitchen', max_length=16)),
                ('qty_ldsp', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('qty_hdf', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('qty_countertops', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('amt_processing', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amt_pvc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amt_facades', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amt_services_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('amt_materials', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('furn_min', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('furn_max', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('furn_avg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='QuickQuoteFacadeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('price_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.priceitem', verbose_name='Тип фасада')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facades', to='core.quickquote')),
            ],
        ),
    ]
