# Generated by Django 5.2.5 on 2025-10-08 09:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_quickquote_quickquotefacadeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickquote',
            name='phone',
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name='QuickQuoteFacade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('price_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.priceitem')),
                ('quick_quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facades', to='core.quickquote')),
            ],
            options={
                'verbose_name': 'БР фасад',
                'verbose_name_plural': 'БР фасады',
            },
        ),
        migrations.DeleteModel(
            name='QuickQuoteFacadeItem',
        ),
    ]
