# Generated by Django 5.2.5 on 2025-11-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_quick_quote_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPaymentInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_services', models.BooleanField(default=True)),
                ('include_design', models.BooleanField(default=True)),
                ('include_facades', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_include', to='core.order')),
            ],
        ),
    ]
