# Generated by Django 5.2.5 on 2025-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_orderpaymentinclude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_iin',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИИН'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Фамилия'),
        ),
    ]
