# Generated by Django 5.2.5 on 2025-11-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_order_customer_iin_order_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_iin',
            new_name='iin',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_last_name',
            new_name='last_name',
        ),
    ]
