# Generated by Django 5.2.5 on 2025-11-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_rename_customer_iin_order_iin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='spec_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Спецификация (JSON)'),
        ),
    ]
