# Generated by Django 5.2.5 on 2025-11-22 10:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_contract_spec_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Месячная заработная плата (брутто)', max_digits=12, verbose_name='Оклад')),
                ('deduction_percent', models.DecimalField(decimal_places=2, default=10, help_text='Процент удержаний (пенсионка + медстраховка)', max_digits=5, verbose_name='Процент отчислений')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Начало периода')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Конец периода')),
                ('pay_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата выплаты')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Начислено (брутто)')),
                ('deduction_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент удержаний')),
                ('deduction_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма удержаний')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='К выплате (нетто)')),
                ('comment', models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Выплата зарплаты',
                'verbose_name_plural': 'Выплаты зарплат',
                'ordering': ['-pay_date', '-id'],
            },
        ),
    ]
