# Generated by Django 5.2.5 on 2025-11-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_employee_salarypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='extra_deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Доп. вычет (штраф и т.п.)'),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='kind',
            field=models.CharField(choices=[('salary', 'Зарплата'), ('advance', 'Аванс')], default='salary', max_length=20, verbose_name='Тип выплаты'),
        ),
    ]
