# Generated by Django 5.2.5 on 2025-11-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_salarypayment_extra_deduction_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='deduction_percent',
        ),
        migrations.AddField(
            model_name='employee',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фиксированная сумма удержаний в месяц (пенсионка, медстраховка и т.п.)', max_digits=12, verbose_name='Удержание, тг'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Должность'),
        ),
    ]
