# Generated by Django 5.2.5 on 2025-11-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_employee_deduction_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Текущий долг по авансам (что ещё нужно удержать из ЗП)', max_digits=12, verbose_name='Баланс авансов, тг'),
        ),
    ]
