# Generated by Django 5.2.5 on 2025-11-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_employee_advance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='materials_alloc_json',
            field=models.JSONField(blank=True, default=list, verbose_name='Распределение материалов (JSON)'),
        ),
    ]
