# Generated by Django 5.2.5 on 2025-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_contract_materials_alloc_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contract_blank_generated',
            field=models.BooleanField(default=False, verbose_name='Бланк договора сформирован (PDF)'),
        ),
    ]
