# Generated by Django 5.2.5 on 2026-01-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_order_contract_blank_generated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(choices=[('general', 'Общий график'), ('technologist', 'График ТЕХНОЛОГ'), ('workshop', 'График ЦЕХ'), ('paint', 'График КРАСКА'), ('film', 'График ПЛЕНКА')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('days_default', models.PositiveIntegerField(default=30)),
                ('group_by', models.CharField(default='day', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
