# Generated by Django 5.2.5 on 2026-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_chartconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chart_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_signed_at',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_film',
            field=models.CharField(choices=[('—', '—'), ('Ожидает', 'Ожидает'), ('ВЫДАН', 'ВЫДАН'), ('СТОП', 'СТОП'), ('ГОТОВО', 'ГОТОВО')], default='—', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='status_paint',
            field=models.CharField(choices=[('—', '—'), ('Ожидает', 'Ожидает'), ('ВЫДАН', 'ВЫДАН'), ('СТОП', 'СТОП'), ('ГОТОВО', 'ГОТОВО')], default='—', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='status_tech',
            field=models.CharField(choices=[('—', '—'), ('Ожидает', 'Ожидает'), ('Корректировка', 'Корректировка'), ('СТОП', 'СТОП'), ('Выдан в ЦЕХ', 'Выдан в ЦЕХ')], default='—', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='status_workshop',
            field=models.CharField(choices=[('—', '—'), ('Ожидает', 'Ожидает'), ('ВЫДАН', 'ВЫДАН'), ('СТОП', 'СТОП'), ('ГОТОВО', 'ГОТОВО')], default='—', max_length=32),
        ),
    ]
