# Generated by Django 5.2.5 on 2026-01-10 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_order_chart_note_order_contract_signed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='main_contract_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='main_contract_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_main_contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
