# Generated by Django 5.2.5 on 2026-01-10 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_order_main_contract_signed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartconfig',
            options={'ordering': ['-effective_from', '-id']},
        ),
        migrations.AddField(
            model_name='chartconfig',
            name='days_film',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='chartconfig',
            name='days_ldsp',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='chartconfig',
            name='days_paint',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='chartconfig',
            name='effective_from',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, help_text='Дата, с которой действуют эти настройки'),
        ),
        migrations.AlterField(
            model_name='chartconfig',
            name='tab',
            field=models.CharField(choices=[('general', 'Общий график'), ('technologist', 'График ТЕХНОЛОГ'), ('workshop', 'График ЦЕХ'), ('paint', 'График КРАСКА'), ('film', 'График ПЛЕНКА')], db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='chartconfig',
            index=models.Index(fields=['tab', 'effective_from'], name='core_chartc_tab_bf4ee3_idx'),
        ),
    ]
