# Generated by Django 5.2.5 on 2026-01-10 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_chartconfig_options_chartconfig_days_film_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartconfig',
            options={'ordering': ['tab', '-effective_from', '-id']},
        ),
        migrations.AlterField(
            model_name='chartconfig',
            name='effective_from',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
