# Generated by Django 5.2.5 on 2026-01-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_chartconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayKZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
