# Generated by Django 5.2.5 on 2026-01-11 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_holidaykz'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_ldsp', models.CharField(choices=[('ОЖИДАЕТ', 'ОЖИДАЕТ'), ('КОРРЕКТИРОВКА', 'КОРРЕКТИРОВКА'), ('СТОП', 'СТОП'), ('ВЫДАН В ЦЕХ', 'ВЫДАН В ЦЕХ'), ('ГОТОВО', 'ГОТОВО'), ('ВЫДАН', 'ВЫДАН')], default='ОЖИДАЕТ', max_length=32)),
                ('status_film', models.CharField(choices=[('ОЖИДАЕТ', 'ОЖИДАЕТ'), ('КОРРЕКТИРОВКА', 'КОРРЕКТИРОВКА'), ('СТОП', 'СТОП'), ('ВЫДАН В ЦЕХ', 'ВЫДАН В ЦЕХ'), ('ГОТОВО', 'ГОТОВО'), ('ВЫДАН', 'ВЫДАН')], default='ОЖИДАЕТ', max_length=32)),
                ('status_paint', models.CharField(choices=[('ОЖИДАЕТ', 'ОЖИДАЕТ'), ('КОРРЕКТИРОВКА', 'КОРРЕКТИРОВКА'), ('СТОП', 'СТОП'), ('ВЫДАН В ЦЕХ', 'ВЫДАН В ЦЕХ'), ('ГОТОВО', 'ГОТОВО'), ('ВЫДАН', 'ВЫДАН')], default='ОЖИДАЕТ', max_length=32)),
                ('due_ldsp_override', models.DateField(blank=True, null=True)),
                ('due_film_override', models.DateField(blank=True, null=True)),
                ('due_paint_override', models.DateField(blank=True, null=True)),
                ('extra_days_ldsp', models.IntegerField(default=0)),
                ('extra_days_film', models.IntegerField(default=0)),
                ('extra_days_paint', models.IntegerField(default=0)),
                ('stop_until', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.order')),
            ],
        ),
    ]
