# Generated by Django 5.2.5 on 2026-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_orderschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderschedule',
            name='status_film',
            field=models.CharField(choices=[('ОТЛОЖЕН', 'ОТЛОЖЕН'), ('ОЖИДАЕТ', 'ОЖИДАЕТ'), ('КОРРЕКТИРОВКА', 'КОРРЕКТИРОВКА'), ('СТОП', 'СТОП'), ('ВЫДАН В ЦЕХ', 'ВЫДАН В ЦЕХ'), ('ГОТОВО', 'ГОТОВО'), ('ВЫДАН', 'ВЫДАН')], default='ОЖИДАЕТ', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='status_ldsp',
            field=models.CharField(choices=[('ОТЛОЖЕН', 'ОТЛОЖЕН'), ('ОЖИДАЕТ', 'ОЖИДАЕТ'), ('КОРРЕКТИРОВКА', 'КОРРЕКТИРОВКА'), ('СТОП', 'СТОП'), ('ВЫДАН В ЦЕХ', 'ВЫДАН В ЦЕХ'), ('ГОТОВО', 'ГОТОВО'), ('ВЫДАН', 'ВЫДАН')], default='ОЖИДАЕТ', max_length=32),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='status_paint',
            field=models.CharField(choices=[('ОТЛОЖЕН', 'ОТЛОЖЕН'), ('ОЖИДАЕТ', 'ОЖИДАЕТ'), ('КОРРЕКТИРОВКА', 'КОРРЕКТИРОВКА'), ('СТОП', 'СТОП'), ('ВЫДАН В ЦЕХ', 'ВЫДАН В ЦЕХ'), ('ГОТОВО', 'ГОТОВО'), ('ВЫДАН', 'ВЫДАН')], default='ОЖИДАЕТ', max_length=32),
        ),
    ]
