# Generated by Django 5.2.5 on 2026-02-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_orderschedule_status_film_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderschedule',
            name='base_due_film',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='base_due_ldsp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='base_due_paint',
            field=models.DateField(blank=True, null=True),
        ),
    ]
