# Generated by Django 5.2.5 on 2026-04-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_orderschedule_done_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderschedule',
            name='done_at_film',
            field=models.DateField(blank=True, null=True, verbose_name='Дата готовности Плёнка'),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='done_at_ldsp',
            field=models.DateField(blank=True, null=True, verbose_name='Дата готовности ЛДСП'),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='done_at_paint',
            field=models.DateField(blank=True, null=True, verbose_name='Дата готовности Краска'),
        ),
    ]
