# Generated by Django 5.2.5 on 2025-09-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_settings_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsettings',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Включить отправку WhatsApp'),
        ),
    ]
